### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#170]
- [x] Close out all other tickets
- [x] Update Screenshots
- [x] Bump version number
- [x] Submit iOS version
- [x] Update User Manual
- [x] Update README, CHANGELOG, etc.
- [x] Generate release builds/installers
- [x] Update website
- [x] Release iOS version
- [x] Merge to `master`
- [x] Tag GitHub Release
- [x] Postings:
  - [x] KVR
  - [x] AudioBus
  - [x] Webpage (news)
  - [x] Patreon
