### ISSUE TITLE
Version 2.9.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#216]
- [x] Close out outstanding issues
- [x] Publish TestFlight build for iOS testing
- [x] Update documentation:
  - [x] User Manual
  - [x] Screenshots
  - [x] Update README, CHANGELOG, BUILDING, etc
- [x] Test on Windows:
  - [x] Ableton
  - [x] FL Studio
  - [x] Reaper
  - [x] Studio One
- [x] Test on Mac:
  - [x] Ableton
  - [x] GarageBand
  - [x] Logic (M1)
  - [x]  FL Studio
- [x] Test on Linux: 
  - [x] Carla
  - [x] Ardour
- [x] Test on iOS:
  - [x] AUM
  - [x] GarageBand
- [x] Bump version number
- [x] Submit iOS build for review
- [x] Generate release builds/installers
- [x] Release iOS version
- [x] Merge to master
- [x] Tag GitHub Release
- [x] Update website
- [x] Postings:
  - [x] KVR
  - [x] AudioBus
  - [x] Webpage (news)
  - [x] Patreon
