### ISSUE TITLE
Version 2.10.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#233]
- [x] Close out outstanding issues
- [x] Bump version number
- [x] Generate AAX builds
- [x] Update documentation:
  - [x] User Manual
  - [x] Screenshots
  - [x] Update README, CHANGELOG, BUILDING, etc
- [x] Test on Windows:
  - [x] Ableton
  - [x] FL Studio
  - [x] Reaper
  - [x] Pro Tools
- [x] Test on Mac:
  - [x] Ableton
  - [x] GarageBand
  - [x] Logic (M1)
  - [x] Pro Tools
- [x] Test on Linux: 
  - [x] Carla
- [x] Test on iOS:
  - [x] AUM
  - [x] GarageBand
- [x] Submit iOS build for review
- [x] Generate release builds/installers
- [x] Release iOS version
- [x] Bump CHANGELOG date
- [x] Merge to master
- [x] Tag GitHub Release
- [x] Update website
  - [x] Update compatibility requirements
  - [x] Update build links
  - [x] Update manual link
- [x] Postings:
  - [x] KVR
  - [x] AudioBus
  - [x] Webpage (news)
  - [x] Patreon
