### ISSUE TITLE
Version 2.11.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#280]
- [x] Close out outstanding issues
- [x] Bump version number
- [x] Update user manual
  - [x] Screenshots
  - [x] New features (esp. accessibility)
- [x] Generate AAX builds
- [x] Test on Windows:
  - [x] Ableton
  - [x] Reaper
  - [x] Bitwig (CLAP)
  - [x] Pro Tools
- [x] Test on Mac:
  - [x] Ableton
  - [x] GarageBand
  - [x] Bitwig (CLAP)
  - [x] Logic (M1)
  - [x] Pro Tools
- [x] Test on iOS:
  - [x] AUM
  - [x] GarageBand
- [x] Submit iOS build for review
- [x] Generate release builds/installers
- [x] Release iOS version
- [x] Update documentation:
  - [x] Update README, CHANGELOG, etc
- [x] Merge to `master` branch
- [x] Tag GitHub Release
- [x] Update website
  - [x] Update build links
